/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import com.marina.entity.creditprogram.CreditProgram;
import controller.CreditProgramController;
import java.util.ArrayList;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marik
 */
public class AdministratorViewport extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    protected ArrayList<CreditProgram> creditProgramsList;
    protected DefaultTableModel creditProgramTableModel;
    protected CreditProgramController creditProgramController = new CreditProgramController();

    /**
     * Creates new form AdministratorForm
     */
    public AdministratorViewport() {
        initComponents();
        creditProgramTableModel = (DefaultTableModel) creditProgramsTable.getModel();
        fillCreditProgramTable();
        setTableCellListener();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        creditProgramsTab = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        creditProgramsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Administrator's frame");

        creditProgramsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Short description", "Full description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        creditProgramsTable.setPreferredSize(new java.awt.Dimension(225, 200));
        jScrollPane3.setViewportView(creditProgramsTable);

        creditProgramsTab.addTab("Credit programs", jScrollPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditProgramsTab, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(creditProgramsTab, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane creditProgramsTab;
    private javax.swing.JTable creditProgramsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void fillCreditProgramTable() {
        creditProgramsList = creditProgramController.getCreditProgramsList();
        for (CreditProgram cp : creditProgramsList) {
            creditProgramTableModel.insertRow(creditProgramsTable.getRowCount(), new Object[]{cp.getTitle(), cp.getShortDescription(), cp.getFullDescription()});
        }
    }

    private void setTableCellListener() {
        creditProgramTableModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                int row = e.getFirstRow();
                int column = e.getColumn();
                String columnName = creditProgramTableModel.getColumnName(column);
                Object data = creditProgramTableModel.getValueAt(row, column);
                System.out.println("e: " + e + " row = " + row + " column: " + column + " data: " + data + " column name: " + columnName);
                updateCreditProgram(creditProgramsList.get(row), 1, (String) data);
            }
        });
    }

    private void updateCreditProgram(CreditProgram creditProgram, int columnId, String data) {
        switch (columnId) {
            case 0:
                creditProgram.setTitle(data);
                break;
            case 1:
                creditProgram.setShortDescription(data);
                break;
            case 2:
                creditProgram.setFullDescription(data);
                break;
        }
        creditProgramController.updateCreditProgram(creditProgram);
    }

}
